In [1]:
import tensorflow as tf
import numpy as np

# <font color='blue'>Making Tensor</font>

In [ ]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)
tensor_one_d = tf.constant([2,0,-3,9.0],dtype=tf.float32)
print(tensor_one_d)

casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.int16)
print(casted_tensor_one_d)
casted_tensor_one_d = tf.cast(tensor_one_d,dtype=tf.bool)
print(casted_tensor_one_d)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 2.  0. -3.  9.], shape=(4,), dtype=float32)
tf.Tensor([ 2  0 -3  9], shape=(4,), dtype=int16)
tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],

    [[10,2,0],
     [1,0,2]],

    [[5,8,9],
     [2,7,0]],

    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  9]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
tensor_four_d = tf.constant([
    [
        [[1,2,0],
         [3,5,-1]],

        [[10,2,0],
         [1,0,2]],

        [[5,8,0],
         [2,73,0]]
    ],
    [
        [[103,26,0],
         [3,50,-12]],

        [[100,2,0],
         [1,0,23]],

        [[5,28,0],
         [2,4,0]]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2  73   0]]]


 [[[103  26   0]
   [  3  50 -12]]

  [[100   2   0]
   [  1   0  23]]

  [[  5  28   0]
   [  2   4   0]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=[3],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=5,
    batch_shape=[2,5],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0.

In [ ]:
fill_tensor = tf.fill(
    [2,3,4],5,name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
ones_tensor = tf.ones(
    [5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


In [ ]:
one_like_tensor = tf.ones_like(
    fill_tensor
)
print(one_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(2, 3, 4), dtype=int32)


In [ ]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name='tensor'
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [ ]:
tf.rank(zeros_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
#No of element in tensor
tf.size(zeros_tensor,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
#Generating random normal distribution tensor
random_tensor = tf.random.normal(
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 0.31281167 -1.7909662 ]
 [ 2.488153    1.6784717 ]
 [ 0.7506212   0.6073117 ]], shape=(3, 2), dtype=float32)


In [ ]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.09076   98.098625]
 [100.52735  100.50709 ]
 [ 99.36864   99.581436]], shape=(3, 2), dtype=float32)


In [ ]:
tf.random.uniform(
    [5,],
    minval=0,
    maxval=5,
  dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([1.9674993 , 0.68987906, 3.788519  , 2.0962281 , 4.1418924 ],
      dtype=float32)>

In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[3,], maxval=5, dtype=tf.int32, seed=20))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([4 1 3], shape=(3,), dtype=int32)


In [ ]:
g = tf.random.Generator.from_non_deterministic_state()
g.normal(shape=(2,2),mean=100,stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 99.91212, 100.46829],
       [ 99.70144, 100.68782]], dtype=float32)>

In [ ]:
g = tf.random.Generator.from_non_deterministic_state()
g.uniform(shape=(2,2), minval = 25, maxval = 40)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[39.671707, 38.430565],
       [25.779352, 32.26012 ]], dtype=float32)>

In [ ]:
tf.random.normal(
    (3,), mean=0.0, stddev=100.0, dtype=tf.dtypes.float32, seed=12, name="Random Number with Normal distribution"
)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([12.151812,  9.970952, 69.518616], dtype=float32)>

In [ ]:
tf.random.uniform(
    (2,), minval=0, maxval=100, dtype=tf.dtypes.float32, seed=None, name=None
)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([62.63931, 52.98432], dtype=float32)>

# <font color='blue'>**Indexing**</font>

In [ ]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
print(tensor_indexed[:])
print(tensor_indexed[0:4])
print(tensor_indexed[3:-3])

tf.Tensor([ 3  6  2  4  6 66  7], shape=(7,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
tf.Tensor([4], shape=(1,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[0:3,:3])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,2,0],
                            [3,5,-1],
                            [1,5,6],
                            [2,3,8]])
print(tensor_two_d[...,1])

tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],
                              [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]


                              ])

print(tensor_three_d[ 2 , 0 , :2])


tf.Tensor([5 8], shape=(2,), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],
                              [3,5,-1]],

                              [[10,2,0],
                               [1,0,2]],

                              [[5,8,0],
                               [2,7,0]],

                              [[2,1,9],
                               [4,-3,32]]


                              ])

print(tensor_three_d[ ... , : , 2])


tf.Tensor(
[[ 0 -1]
 [ 0  2]
 [ 0  0]
 [ 9 32]], shape=(4, 2), dtype=int32)


In [ ]:
print(tf.expand_dims(tensor_three_d[ ... , : , 2],-1))

tf.Tensor(
[[[ 0]
  [-1]]

 [[ 0]
  [ 2]]

 [[ 0]
  [ 0]]

 [[ 9]
  [32]]], shape=(4, 2, 1), dtype=int32)


# <font color='blue'>**Maths Operations**</font>

In [ ]:
x_abs = tf.constant([-2.25, 3.25])
tf.abs(x_abs)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [ ]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)


<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [ ]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [ ]:

x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.add(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [10.  8. 11. 11.  9. 11.]
 [ 8.  6.  9.  9.  7.  9.]], shape=(3, 6), dtype=float32)


In [ ]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [ ]:
x = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x.shape)
print(tf.math.argmax(x,axis=0))#column wise maximum

(3, 5)
tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)


In [ ]:
x = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x.shape)
print(tf.math.argmin(x,axis=1))#row-wise minimum

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [ ]:
x = tf.constant([[2, 2], [3, 3]])
y = tf.constant([[3, 0], [1, 4]])
tf.pow(x, y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]], dtype=int32)>

In [ ]:
tf.pow(tf.constant(2) ,tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_sum(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[  7.  11. 114.]], shape=(1, 3), dtype=float16)


In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_max(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[  3.   5. 100.]], shape=(1, 3), dtype=float16)


In [ ]:
#Computes the standard deviation of elements across dimensions of a tensor.
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [ ]:
#Finds values and indices of the k largest entries for the last dimension.
tf.math.top_k(tensor_two_d, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]], dtype=int32)>)

# <font color='blue'>**Linear Algebra Operations**</font>

In [ ]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)

(1, 3) (3, 2) (2, 4) (2, 3)


In [ ]:
print(tf.transpose(x_3)@tf.transpose(x_2))

tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


In [ ]:
x11 =tf.constant([[1,2,0]])
x22 = tf.constant([[1,2,0,3],
                  [3,5,1,-2],
                  [4,5,6,8]])

print(x11.shape,x22.shape)
tf.linalg.matmul(
    x11, x22, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 4)


<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12,  2, -1]], dtype=int32)>

In [ ]:
x11@x22

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 7, 12,  2, -1]], dtype=int32)>

In [ ]:
tf.transpose(x22)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  3,  4],
       [ 2,  5,  5],
       [ 0,  1,  6],
       [ 3, -2,  8]], dtype=int32)>

In [ ]:
x_1 =  tf.constant([[[1,2],
                    [3,5]],

                    [[10,0],
                    [1,2]],

                    [[5,0],
                    [2,0]]])

x_2 = tf.constant([[[5,1,4],
                    [34,15,1]],

                    [[1,2,2],
                    [5,3,2]],

                    [[2,2,3],
                    [1,1,1]]])

print(tf.linalg.matmul(x_1, x_2))

tf.Tensor(
[[[ 73  31   6]
  [185  78  17]]

 [[ 10  20  20]
  [ 11   8   6]]

 [[ 10  10  15]
  [  4   4   6]]], shape=(3, 2, 3), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0, 0)#Diagonal

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]], dtype=float16)>

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, -1, 0)#Lower Triangular

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[1., 0., 0.],
       [3., 5., 0.],
       [1., 5., 6.],
       [2., 3., 8.]], dtype=float16)>

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)

tensor_out_d = tf.constant([[1,0,0],
                            [0,5,0],
                            [0,0,6],
                            [0,0,0]], dtype = tf.float16)

#### ( m-n <= lower) and ( n-m <= upper)
# m -- rows, n --- columns
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  1.,  -2.,   0.],
       [  0.,   5., 100.],
       [  0.,   0.,   6.],
       [  0.,   0.,   0.]], dtype=float16)>

In [ ]:
tensor_two_d_m_n = tf.constant([[0,-1,-2],
                                [1,0,-1],
                                [2,1,0],
                                [3,2,1]], dtype = tf.float16)

tensor_two_d_n_m = tf.constant([[0,1,2],
                                [-1,0,1],
                                [-2,-1,0],
                                [-3,-2,-1]], dtype = tf.float16)

#m = 1, n = 2

In [ ]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)
print(tensor_two_d_inv)

tf.Tensor(
[[ 0.7413249  -0.01892742  0.3154574 ]
 [-0.12933755 -0.00946371  0.1577287 ]
 [-0.01577287  0.01104101 -0.01735016]], shape=(3, 3), dtype=float32)


In [ ]:
tensor_two_d1 = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6]], dtype = tf.float32)
s,u,v = tf.linalg.svd(tensor_two_d1)
print(s)
print(u)
print(v)

tf.Tensor([100.3663      5.1059036   1.2371687], shape=(3,), dtype=float32)
tf.Tensor(
[[-7.4980810e-04 -3.7569830e-01  9.2674178e-01]
 [ 9.9803799e-01 -5.8300879e-02 -2.2827482e-02]
 [ 6.2606096e-02  9.2490643e-01  3.7500489e-01]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.03044816  0.07330841  0.99684453]
 [ 0.0528536   0.9957936  -0.07484547]
 [ 0.998138   -0.05496572 -0.02644547]], shape=(3, 3), dtype=float32)


# <font color='blue'>Ragged Tensors</font>

In [ ]:
tensor_two = [[1,2,4,5],
              [3],
              [4,5,6,7,89,4],
              [4,1,4]]
tensor_ragged = tf.ragged.constant(tensor_two)
print(tensor_ragged.shape)

(4, None)


In [ ]:
print(tf.RaggedTensor.from_row_lengths(values=[2,3,4,6,7,8,9],row_lengths=[4,2,0,1,0]))

<tf.RaggedTensor [[2, 3, 4, 6], [7, 8], [], [9], []]>


In [ ]:
tensor_three_d = tf.constant([[[1,2,0],
                             [3,5,-1]],

                            [[10,2,0],
                             [1,0,2]],

                            [[5,8,0],
                             [2,7,0]],

                            [[2,1,9],
                             [4,-3,32]]])
print(tensor_three_d.shape)
x_exp = tf.expand_dims(tensor_three_d, axis = 3)
print(x_exp.shape)
print(tf.squeeze(x_exp, axis = 3))
print(tf.reshape(x_exp, [4,2,3]))

(4, 2, 3)
(4, 2, 3, 1)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
x = tf.constant([[[2,3,4,5]]])
print(x.shape)
x_expanded = tf.expand_dims(x, axis = 0)
print(x_expanded)

(1, 1, 4)
tf.Tensor([[[[2 3 4 5]]]], shape=(1, 1, 1, 4), dtype=int32)


In [ ]:
x_squeezed = tf.squeeze(x_expanded, axis = 0)
for i in range(2):
  x_squeezed = tf.squeeze(x_squeezed, axis = 0)

print(x_squeezed)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
x_reshape = tf.constant([[3,5,6,6],
                         [4,6,-1,2]])

print(tf.reshape(x_reshape, [-1]))
print(tf.reshape(x_reshape, [8]))

tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)
tf.Tensor([ 3  5  6  6  4  6 -1  2], shape=(8,), dtype=int32)


In [ ]:
t1 = [[1, 2, 3],
      [4, 5, 6],
      [5, 6, 2],
      [1, 2, 1]]

t2 = [[7, 8, 9],
      [10, 11, 12],
      [0, 0, 2],
      [-1, 5, 2]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

tf.concat([t1, t2], axis = 0)

(4, 3)
(4, 3)


<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  2],
       [ 1,  2,  1],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  0,  2],
       [-1,  5,  2]], dtype=int32)>

In [ ]:
tf.stack([t1,t2], axis = 2)

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  7],
        [ 2,  8],
        [ 3,  9]],

       [[ 4, 10],
        [ 5, 11],
        [ 6, 12]],

       [[ 5,  0],
        [ 6,  0],
        [ 2,  2]],

       [[ 1, -1],
        [ 2,  5],
        [ 1,  2]]], dtype=int32)>

In [ ]:
tf.stack([t1,t2], axis = 0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

In [ ]:
tf.concat([tf.expand_dims(t, axis = 0) for t in [t1,t2]], axis = 0)

#1,4,3 - 1,4,3 --> 2,4,3

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0,  2],
        [-1,  5,  2]]], dtype=int32)>

In [ ]:
t = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

paddings = tf.constant([[1, 5,],
                        [2, 3]])

tf.pad(t, paddings, "CONSTANT", constant_values = 0)

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
print(params.shape)
params[1:3+1]

(6,)


<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [ ]:
tf.gather(params, [0,5,3], axis = 0)

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [ ]:
indices = [[[0, 1],
            [1, 0]],

            [[0, 0],
             [1, 1]]]

params = [[['a0', 'b0'],
           ['c0', 'd0']],

          [['a1', 'b1'],
           ['c1', 'd1']]]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>

In [ ]:
tensor_string = tf.constant(["hello", "i am ", "a string"])
print(tensor_string)

tf.Tensor([b'hello' b'i am ' b'a string'], shape=(3,), dtype=string)


In [ ]:
tf.strings.join(tensor_string, separator="+")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello+i am +a string'>

In [ ]:
with tf.device('CPU:0'):
  x_1 = tf.constant([1,3,4])
  x_2 = tf.constant([1])

with tf.device('GPU:0'):
  x_3 = x_1 + x_2

print(x_1, x_1.device)
print(x_2, x_2.device)
print(x_3, x_3.device)

tf.Tensor([1 3 4], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([1], shape=(1,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0
tf.Tensor([2 4 5], shape=(3,), dtype=int32) /job:localhost/replica:0/task:0/device:CPU:0


# <font color='blue'>**Gradient**</font>

In [4]:
inp_var = tf.Variable(initial_value=10.)
with tf.GradientTape() as grad:
  result = tf.square(inp_var)
gradient = grad.gradient(result,inp_var)

In [6]:
print(gradient)

tf.Tensor(20.0, shape=(), dtype=float32)


In [7]:
inp_const = tf.constant(10.)
with tf.GradientTape() as tape:
  tape.watch(inp_const)
  result = tf.square(inp_const)
grad = tape.gradient(result,inp_const)

In [8]:
print(grad)

tf.Tensor(20.0, shape=(), dtype=float32)
